sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install i -g @angular/cli
- npm install i -g angular-cli-ghpages
- npm install
- ng build --prod --base-href "https://craigles.github.io/ng-auth0/"
- angular-cli-ghpages --repo=https://GH_TOKEN@github.com/craigles/ng-auth0.git

script: karma start karma.conf.js --single-run